VERSION: str = "2.0.0"
APP_NAME: str = "Azure AKS + LLM Cost Simulator"
APP_DATE: str = "June 2026"
AUTHOR: str = ""

HOURS_PER_MONTH: int = 730
HOURS_PER_DAY: int = 24
DAYS_PER_MONTH: int = 30

DEFAULT_MARGIN_CPU: float = 0.2
DEFAULT_MARGIN_RAM: float = 0.2
DEFAULT_HA_FACTOR: float = 1.15
DEFAULT_OVERHEAD_FACTOR: float = 0.1
DEFAULT_GPU_UTILIZATION: float = 0.75
DEFAULT_SAFETY_FACTOR: float = 1.0
DEFAULT_THROUGHPUT_A100: int = 350
DEFAULT_THROUGHPUT_A10: int = 120

MONTE_CARLO_ITERATIONS: int = 10_000
MONTE_CARLO_TRAFFIC_VARIATION: float = 0.20
MONTE_CARLO_PEAK_DURATION_VARIATION: float = 0.30
MONTE_CARLO_THROUGHPUT_VARIATION: float = 0.10
MONTE_CARLO_PRICING_VARIATION: float = 0.05

DEFAULT_OUTPUT_XLSX: str = "resultados_simulacion.xlsx"
DEFAULT_OUTPUT_CSV: str = "resultados_simulacion.csv"
DEFAULT_CHART_FILE: str = "comparativa_costes.png"

# Load defaults
DEFAULT_USERS: int = 6_000
DEFAULT_INTERACTIONS_PER_USER_DAY: int = 20
DEFAULT_INPUT_TOKENS: int = 2_000
DEFAULT_OUTPUT_TOKENS: int = 400
DEFAULT_WORKING_DAYS: int = 22
DEFAULT_OFFICE_HOURS: int = 10
DEFAULT_PEAK_HOURS: float = 2.0
DEFAULT_CONCURRENT_RATIO: float = 0.15
DEFAULT_PEAK_MULTIPLIER: float = 2.0

# VM pricing (Azure West Europe)
DEFAULT_SYSTEM_VM: str = "Standard_D8ds_v5"
DEFAULT_SYSTEM_PRICE: float = 0.80
DEFAULT_SYSTEM_NODES: int = 1

DEFAULT_IDEAL_GPU_VM: str = "Standard_NC24ads_A100_v4"
DEFAULT_IDEAL_GPU_PRICE: float = 6.00
DEFAULT_IDEAL_THROUGHPUT: int = 350

DEFAULT_ECO_GPU_VM: str = "Standard_NV12ads_A10_v5"
DEFAULT_ECO_GPU_PRICE: float = 2.20
DEFAULT_ECO_THROUGHPUT: int = 120

# Fixed infra costs (EUR/month)
DEFAULT_STORAGE_IDEAL: float = 200.0
DEFAULT_STORAGE_ECO: float = 140.0
DEFAULT_LB: float = 60.0
DEFAULT_MONITOR_IDEAL: float = 150.0
DEFAULT_MONITOR_ECO: float = 120.0
DEFAULT_ACR_IDEAL: float = 140.0
DEFAULT_ACR_ECO: float = 100.0

# API defaults
DEFAULT_API_MODEL: str = "gpt-4o"
DEFAULT_API_INPUT_PRICE: float = 2.50
DEFAULT_API_OUTPUT_PRICE: float = 10.00
DEFAULT_EUR_USD: float = 0.92
